#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'
module EsiAttributeLanguageibute
  class Parser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
     7,     7,     8,    10,     7,     5,     5,    11,     9,     5,
     7,    15,     4,    11,     9,     5,    11,     9,    11,     9,
     3,     1 ]

racc_action_check = [
     7,     9,     4,     6,    11,     7,     9,     6,     6,    11,
     3,    12,     2,    12,    12,     3,    13,    13,    14,    14,
     1,     0 ]

racc_action_pointer = [
    19,    15,    12,     3,     2,   nil,    -3,    -7,   nil,    -6,
   nil,    -3,     3,     6,     8,   nil ]

racc_action_default = [
    -6,    -6,    -6,    -6,    -6,    -5,    -6,    -6,    16,    -6,
    -1,    -6,    -6,    -4,    -2,    -3 ]

racc_goto_table = [
     6,     2,   nil,   nil,    12,   nil,    13,   nil,    14 ]

racc_goto_check = [
     2,     1,   nil,   nil,     2,   nil,     2,   nil,     2 ]

racc_goto_pointer = [
   nil,     1,    -3 ]

racc_goto_default = [
   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  4, 14, :_reduce_none,
  3, 15, :_reduce_2,
  3, 15, :_reduce_3,
  3, 15, :_reduce_4,
  1, 15, :_reduce_5 ]

racc_reduce_n = 6

racc_shift_n = 16

racc_token_table = {
  false => 0,
  :error => 1,
  :DOLLAR => 2,
  :LSQUARE => 3,
  :RSQUARE => 4,
  :LPAREN => 5,
  :RPAREN => 6,
  :LBRACE => 7,
  :RBRACE => 8,
  :BSLASH => 9,
  :PIPE => 10,
  :PLUS => 11,
  :NUMBER => 12 }

racc_nt_base = 13

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "DOLLAR",
  "LSQUARE",
  "RSQUARE",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "BSLASH",
  "PIPE",
  "PLUS",
  "NUMBER",
  "$start",
  "varaible",
  "expression" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'parser.y', 10)
  def _reduce_2(val, _values, result)
     result = val[0] rescue val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 11)
  def _reduce_3(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 12)
  def _reduce_4(val, _values, result)
     result = val[0] + val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 13)
  def _reduce_5(val, _values, result)
     result = val[0].to_i 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module EsiAttributeLanguageibute
