#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'
module EsiAttributeLanguage
  class SimpleGrammarParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
     1,     1,     1,     8,    10,     3,     3,     3,    11,    12,
    11,    12,     5,     4,     9,    15,     8,    16 ]

racc_action_check = [
     0,    10,     3,    11,     7,     0,    10,     3,     7,     7,
    14,    14,     2,     1,     5,    12,     4,    15 ]

racc_action_pointer = [
    -2,    10,    12,     0,     9,    14,   nil,     0,   nil,   nil,
    -1,    -4,     8,   nil,     2,     7,   nil ]

racc_action_default = [
    -8,    -8,    -8,    -2,    -8,    -8,    -4,    -8,    -7,    17,
    -1,    -8,    -8,    -3,    -5,    -8,    -6 ]

racc_goto_table = [
     2,     7,   nil,     6,   nil,   nil,   nil,   nil,    14,   nil,
    13 ]

racc_goto_check = [
     1,     2,   nil,     1,   nil,   nil,   nil,   nil,     2,   nil,
     1 ]

racc_goto_pointer = [
   nil,     0,    -3 ]

racc_goto_default = [
   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  4, 13, :_reduce_1,
  1, 13, :_reduce_2,
  5, 13, :_reduce_3,
  2, 13, :_reduce_4,
  3, 14, :_reduce_5,
  4, 14, :_reduce_6,
  1, 14, :_reduce_7 ]

racc_reduce_n = 8

racc_shift_n = 17

racc_token_table = {
  false => 0,
  :error => 1,
  :DOLLAR => 2,
  :LPAREN => 3,
  :RPAREN => 4,
  :STRING => 5,
  :VARIABLE => 6,
  :OTHER => 7,
  :PIPE => 8,
  :LBRACE => 9,
  :RBRACE => 10,
  :QUOTE => 11 }

racc_nt_base = 12

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "DOLLAR",
  "LPAREN",
  "RPAREN",
  "STRING",
  "VARIABLE",
  "OTHER",
  "PIPE",
  "LBRACE",
  "RBRACE",
  "QUOTE",
  "$start",
  "expression",
  "variable" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'simple.y', 6)
  def _reduce_1(val, _values, result)
     result = val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'simple.y', 7)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'simple.y', 8)
  def _reduce_3(val, _values, result)
     result = ConcatNode.new(val[2], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'simple.y', 9)
  def _reduce_4(val, _values, result)
     result = ConcatNode.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'simple.y', 13)
  def _reduce_5(val, _values, result)
     result = OrNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'simple.y', 14)
  def _reduce_6(val, _values, result)
     result = HashLookupNode.new(val[0], Node.cleanse_string(val[2])) 
    result
  end
.,.,

module_eval(<<'.,.,', 'simple.y', 15)
  def _reduce_7(val, _values, result)
     result = VariableLookup.new(val[0]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class SimpleGrammarParser
  end   # module EsiAttributeLanguage
